(() => {
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=rows=>rows.map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join('');
const rpc=async(db,name,args)=>{const r=await db.rpc(name,args);if(r.error)throw r.error;return r.data;};
function exportJSON(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
window.MNCS_AWARDS_DESK={async mount(parent,db,profile,categories,cycles){
 const host=document.createElement('section');host.className='awards-desk';parent.appendChild(host);if(!db){host.textContent='Connect the registry to use awards.';return;}
 let year=window.MNCS_AWARDS_YEAR||cycles.find(c=>c.nomination_status==='Open')?.year||cycles[0]?.year||new Date().getFullYear();
 let category=window.MNCS_SELECTED_AWARD||categories[0].id;
 const admin=profile?.role==='admin',judge=profile?.role==='judge',auditor=profile?.role==='auditor';
 const reload=async()=>{window.MNCS_AWARDS_YEAR=Number(year);window.MNCS_SELECTED_AWARD=category;await window.renderAwards();};
 try{
 const publicRows=await rpc(db,'public_awards',{});
 host.innerHTML=`<section class="fan-poll"><h3>Fan choice · just for fun</h3><p>Judges decide official awards. Fan votes have zero weight in official scores. One vote per verified email per category; totals appear after results are published.</p>${!profile?'<form id="fan-email-form"><label>Your email<input name="email" type="email" required autocomplete="email"></label><button>Send sign-in code</button></form><form id="fan-code-form" hidden><label>Verification code<input name="token" required autocomplete="one-time-code" inputmode="numeric"></label><button>Verify email</button></form>':''}<p id="fan-notice" role="status"></p>${(publicRows||[]).map(row=>`<div class="fan-category"><h4>${row.year} · ${esc(categories.find(c=>c.id===row.category)?.name||row.category)}</h4><p>${esc(row.pollStatus==='Open'?'Fan poll is open':'Fan poll is closed')}</p>${row.candidates.map(c=>`<div class="fan-candidate"><span>${esc(c.name)}${c.votes!==null?' · '+c.votes+' fan votes':''}</span>${row.pollStatus==='Open'?`<button data-fan-vote="${c.id}">${profile?'Vote for this finalist':'Verify email to vote'}</button>`:''}</div>`).join('')}${row.results?`<h4>Official audited results</h4><p>Joint winners share first place if judge totals tie.</p><ol>${row.results.map(r=>`<li>Rank ${r.rank}: <strong>${esc(r.name)}</strong> · ${Number(r.score).toFixed(2)} / 100</li>`).join('')}</ol><p class="source-note">Certified ${esc(row.certifiedAt)} · SHA-256 ${esc(row.fingerprint)}</p>`:''}</div>`).join('')||'<p>MNCS has not published any finalists or opened a fan poll yet.</p>'}</section><div id="official-awards-desk"></div>`;
 let voterEmail='';host.querySelector('#fan-email-form')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{voterEmail=new FormData(e.target).get('email').trim();const r=await db.auth.signInWithOtp({email:voterEmail,options:{shouldCreateUser:true,emailRedirectTo:location.origin+'/index.html#awards'}});if(r.error)throw r.error;host.querySelector('#fan-code-form').hidden=false;host.querySelector('#fan-notice').textContent='Check your email for the code or sign-in link.';}catch(err){host.querySelector('#fan-notice').textContent=err.message;}finally{b.disabled=false;}});
 host.querySelector('#fan-code-form')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const r=await db.auth.verifyOtp({email:voterEmail,token:new FormData(e.target).get('token').trim(),type:'email'});if(r.error)throw r.error;await rpc(db,'register_fan_profile',{});await window.MNCS_REFRESH_PORTAL?.();await reload();}catch(err){host.querySelector('#fan-notice').textContent=err.message;}finally{b.disabled=false;}});
 host.querySelectorAll('[data-fan-vote]').forEach(b=>b.onclick=async()=>{if(!profile){host.querySelector('#fan-notice').textContent='Verify your email above, then choose your finalist.';host.querySelector('#fan-email-form input')?.focus();return;}b.disabled=true;try{await rpc(db,'cast_fan_vote',{candidate:b.dataset.fanVote});host.querySelector('#fan-notice').textContent='Your fan vote is recorded. It does not affect the judges’ award.';}catch(err){host.querySelector('#fan-notice').textContent=err.code==='23505'?'You have already voted in this category.':err.message;}finally{b.disabled=false;}});
 if(!admin&&!judge&&!auditor)return;
 const [configs,candidates,assignments,ballots,audits]=await Promise.all(['award_categories','award_candidates','award_assignments','award_ballots','award_audits'].map(t=>window.MNCS_SPORTS.all(db,t)));
 const roleCategories=admin?categories:categories.filter(c=>assignments.some(a=>a.year===Number(year)&&a.category===c.id&&a.user_id===profile.id));
 if(!roleCategories.some(c=>c.id===category))category=roleCategories[0]?.id||category;
 const desk=host.querySelector('#official-awards-desk');const cfg=configs.find(g=>g.year===Number(year)&&g.category===category),selected=categories.find(c=>c.id===category),finalists=candidates.filter(c=>c.year===Number(year)&&c.category===category),assigned=assignments.filter(a=>a.year===Number(year)&&a.category===category),audit=audits.find(a=>a.year===Number(year)&&a.category===category);
 desk.innerHTML=`<h3>${admin?'MNCS awards control':judge?'Your assigned judging':'Independent audit'}</h3><div class="sports-toolbar"><label>Awards year<select id="official-year">${options([...new Set([...cycles.map(c=>c.year),year])].map(y=>[y,y]))}</select></label><label>Category<select id="official-category">${options(roleCategories.map(c=>[c.id,c.name]))}</select></label></div><p>${esc(cfg?.phase||'Set up this category')} · ${finalists.length} finalists · ${assigned.filter(a=>a.duty==='judge').length} judges</p><p id="official-notice" role="status"></p><div id="official-actions"></div>`;
 desk.querySelector('#official-year').value=String(year);desk.querySelector('#official-category').value=category;
 desk.querySelector('#official-year').onchange=e=>{year=Number(e.target.value);reload();};desk.querySelector('#official-category').onchange=e=>{category=e.target.value;reload();};
 const actions=desk.querySelector('#official-actions');
 const run=async(button,name,args)=>{button.disabled=true;try{await rpc(db,name,args);await reload();}catch(err){desk.querySelector('#official-notice').textContent=err.code==='23505'?'This item has already been saved or submitted.':err.message;}finally{button.disabled=false;}};
 if(admin){
 const profiles=await window.MNCS_SPORTS.all(db,'profiles');const noms=(await window.MNCS_SPORTS.all(db,'submissions')).filter(s=>s.kind==='Award nomination'&&s.status==='Approved'&&s.period===String(year)&&(category==='personality'||s.payload.categoryId===category));
 const rubric=cfg?.rubric||selected.criteriaSummary.map((label,i,list)=>({label,weight:i===list.length-1?100-Math.floor(100/list.length)*(list.length-1):Math.floor(100/list.length)}));
 actions.innerHTML=`${!cfg||cfg.phase==='Preparing'?`<details ${!cfg?'open':''}><summary>1. Agree the judging criteria</summary><form id="rubric-form"><p>Scores are 0–10 per criterion. Weights must total 100%. Equal final totals produce joint winners.</p>${rubric.map((r,i)=>`<label>${esc(r.label)} (%)<input name="weight-${i}" type="number" min="0.01" max="100" step="0.01" value="${r.weight}" required></label>`).join('')}<label>Required judges<input name="quorum" type="number" min="1" max="7" value="${cfg?.minimum_judges||5}" required></label><label><input name="approved" type="checkbox" required> MNCS has approved these weights and the joint-winner tie rule</label><button>Save approved criteria</button></form></details>${cfg?`<details open><summary>2. Add finalists and assign officials</summary><form id="shortlist-form"><label>Eligibility-approved nomination<select name="nomination" required><option value="">Choose nominee</option>${options(noms.filter(n=>!finalists.some(c=>c.nomination_id===n.id)).map(n=>[n.id,n.payload.nomineeName+' · '+getAssociation(n.association_id).name]))}</select></label><label><input name="consent" type="checkbox" required> Up to three finalists. Permission to publish this finalist's name is confirmed</label><button>Add finalist</button></form><ul>${finalists.map(c=>`<li>${esc(c.nominee_name)} <button type="button" data-remove-finalist="${c.id}">Remove from shortlist</button></li>`).join('')}</ul><form id="official-assignment-form"><label>Judge or auditor<select name="official" required><option value="">Choose account</option>${options(profiles.filter(p=>['judge','auditor'].includes(p.role)).filter(p=>!assigned.some(a=>a.user_id===p.id)).map(p=>[p.id,(p.display_name||p.email||p.id)+' · '+p.role]))}</select></label><button>Assign official</button></form><p>${assigned.map(a=>esc(profiles.find(p=>p.id===a.user_id)?.display_name||a.user_id)+' ('+a.duty+') <button type="button" data-remove-official="'+a.user_id+'">Remove</button>').join(' · ')||'No officials assigned yet.'}</p></details><button id="open-judging">3. Open judging</button>`:''}`:''}${cfg?.phase==='Judging'?'<p>Judges can now submit their sealed ballots. Assignments and weights are locked.</p><button id="close-judging">Close judging and send to auditor</button>':''}${cfg&&['Judging','Auditing'].includes(cfg.phase)?`<button id="fan-poll-control">${cfg.poll_status==='Open'?'Close':'Open'} separate fan poll</button>`:''}${cfg?.phase==='Auditing'?`<p>${audit?'Independent audit completed.':'Waiting for the assigned auditor to certify the ballots.'}</p>${audit?'<button id="publish-awards">Publish certified official results</button>':''}`:''}${audit?'<button id="admin-audit-download">Download confidential audit record</button>':''}`;
 actions.querySelectorAll('[data-remove-official]').forEach(b=>b.onclick=()=>run(b,'remove_award_official',{y:Number(year),c:category,official_id:b.dataset.removeOfficial}));
 actions.querySelectorAll('[data-remove-finalist]').forEach(b=>b.onclick=()=>run(b,'remove_award_finalist',{candidate:b.dataset.removeFinalist}));
 actions.querySelector('#rubric-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);run(e.target.querySelector('button'),'configure_award_category',{y:Number(year),c:category,criteria:rubric.map((r,i)=>({label:r.label,weight:Number(f.get('weight-'+i))})),quorum:Number(f.get('quorum'))});});
 actions.querySelector('#shortlist-form')?.addEventListener('submit',e=>{e.preventDefault();run(e.target.querySelector('button'),'shortlist_award',{y:Number(year),c:category,nomination:new FormData(e.target).get('nomination'),consent_confirmed:true});});
 actions.querySelector('#official-assignment-form')?.addEventListener('submit',e=>{e.preventDefault();const id=new FormData(e.target).get('official');run(e.target.querySelector('button'),'assign_award_official',{y:Number(year),c:category,official_id:id,official_duty:profiles.find(p=>p.id===id).role});});
 for(const [id,next_phase] of [['open-judging','Judging'],['close-judging','Auditing'],['publish-awards','Published']])actions.querySelector('#'+id)?.addEventListener('click',e=>run(e.target,'set_award_phase',{y:Number(year),c:category,next_phase}));
 actions.querySelector('#fan-poll-control')?.addEventListener('click',e=>run(e.target,'set_fan_poll',{y:Number(year),c:category,opened:cfg.poll_status!=='Open'}));
 actions.querySelector('#admin-audit-download')?.addEventListener('click',()=>exportJSON('MNCS-confidential-audit-'+year+'-'+category+'.json',audit));
 }
 if(judge){actions.innerHTML=!cfg||cfg.phase!=='Judging'?'<p>Judging is not open for this assigned category.</p>':finalists.map(c=>{const sealed=ballots.find(b=>b.candidate_id===c.id&&b.judge_id===profile.id);return `<article class="sport-record-card"><h4>${esc(c.nominee_name)}</h4><button data-dossier="${c.nomination_id}">Read nomination and evidence</button>${sealed?'<p>Ballot submitted and sealed.</p>':`<form data-judge-form="${c.id}">${cfg.rubric.map((r,i)=>`<label>${esc(r.label)} · weight ${r.weight}%<input name="mark-${i}" type="number" min="0" max="10" step="0.1" required></label>`).join('')}<label>Reason for your assessment<textarea name="reason" maxlength="3000" required></textarea></label><label><input name="conflict" type="checkbox" required> I have no unresolved conflict of interest with this nominee</label><p>Submitting seals this ballot. Review your marks before submitting.</p><button>Submit and seal ballot</button></form>`}</article>`;}).join('');
 actions.querySelectorAll('[data-judge-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const data=new FormData(f);run(f.querySelector('button'),'submit_award_ballot',{candidate:f.dataset.judgeForm,marks:cfg.rubric.map((_,i)=>Number(data.get('mark-'+i))),reason:data.get('reason'),no_conflict:data.get('conflict')==='on'});});}
 if(auditor){const scored=ballots.filter(b=>finalists.some(c=>c.id===b.candidate_id));actions.innerHTML=!cfg||!['Auditing','Published'].includes(cfg.phase)?'<p>Ballots stay confidential until MNCS closes judging.</p>':`<p>Review nomination eligibility, conflicts, assignments and every sealed ballot before certification.</p><button id="audit-export">Download confidential ballots and criteria</button><div class="overflow-x-auto"><table><thead><tr><th>Finalist</th><th>Judge ID</th><th>Marks</th><th>Weighted score</th><th>Rationale</th></tr></thead><tbody>${scored.map(b=>`<tr><td>${esc(finalists.find(c=>c.id===b.candidate_id)?.nominee_name)}</td><td>${esc(b.judge_id)}</td><td>${esc(b.scores.join(', '))}</td><td>${Number(b.score).toFixed(2)}</td><td>${esc(b.rationale)}</td></tr>`).join('')}</tbody></table></div>${audit?`<p>Certified snapshot: ${esc(audit.fingerprint)}</p><button id="certified-audit-export">Download certified audit</button>`:`<form id="audit-certification-form"><label>Independent audit statement<textarea name="statement" minlength="20" maxlength="3000" required></textarea></label><label><input type="checkbox" required> I independently verified the records and recomputed the scores</label><button>Certify the official results</button></form>`}`;
 actions.querySelector('#audit-export')?.addEventListener('click',()=>exportJSON('MNCS-private-ballots-'+year+'-'+category+'.json',{category:cfg,assignments:assigned,candidates:finalists,ballots:scored}));actions.querySelector('#certified-audit-export')?.addEventListener('click',()=>exportJSON('MNCS-certified-audit-'+year+'-'+category+'.json',audit));actions.querySelector('#audit-certification-form')?.addEventListener('submit',e=>{e.preventDefault();run(e.target.querySelector('button'),'certify_award',{y:Number(year),c:category,audit_statement:new FormData(e.target).get('statement')});});
 }
 actions.querySelectorAll('[data-dossier]').forEach(b=>b.onclick=async()=>{try{const r=await db.from('submissions').select('*').eq('id',b.dataset.dossier).maybeSingle();if(r.error)throw r.error;const s=r.data;if(!s)throw Error('Nomination unavailable');const view=document.createElement('details');view.open=true;view.className='dossier-detail';view.innerHTML=`<summary>Private nomination details</summary><p>${esc(s.payload.description)}</p><p>${esc(s.payload.motivation)}</p>`;b.after(view);if(s.document_path){const doc=await db.storage.from('association-documents').createSignedUrl(s.document_path,60);if(doc.error)throw doc.error;const link=document.createElement('a');link.href=doc.data.signedUrl;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Open private evidence PDF';view.appendChild(link);}}catch(err){desk.querySelector('#official-notice').textContent=err.message;}});
 }catch(error){host.textContent=admin?'Awards desk unavailable: '+error.message+'. Install the complete V1.0 SQL update.':'Awards participation is being prepared. Please try again later.';}
}};
})();
