// Isolated sports simulator. This is a walkthrough, not a substitute for database tests.
(() => {
const {tables,db}=window.MNCS_DEMO;
tables.sport_records=[];tables.ranking_policies=[];
const oldRpc=db.rpc.bind(db),error=message=>({data:null,error:{message}}),ok=data=>({data,error:null});
const approved=(id,kind,owner)=>tables.sport_records.find(r=>r.id===id&&r.kind===kind&&r.association_id===owner&&r.published_payload&&r.status!=='Archived');
const uid=()=>crypto.randomUUID();
function validate(owner,kind,v,id){
 if(['Athlete','Team','Competition'].includes(kind)&&(!v.name?.trim()||!v.discipline?.trim()||!v.category?.trim()))throw Error('Name, discipline and category required.');
 if(kind==='Competition'&&(!v.startDate||!v.endDate||v.endDate<v.startDate))throw Error('Invalid competition dates.');
 if(kind==='Competition'&&v.rankingPolicyId){const p=tables.ranking_policies.find(p=>p.id===v.rankingPolicyId);if(!p||p.association_id!==owner||p.discipline!==v.discipline||p.category!==v.category||p.season!==Number(v.season))throw Error('Ranking rule must match the competition.');}
 if(['Fixture','Result'].includes(kind)){
  const c=approved(v.competitionId,'Competition',owner);if(!c)throw Error('An approved competition is required.');
  const check=(key,type)=>{const p=approved(key,type,owner);if(!p||p.published_payload.discipline!==c.published_payload.discipline||p.published_payload.category!==c.published_payload.category)throw Error('Approved participant must match discipline and category.');};
  if(kind==='Fixture'){check(v.homeTeamId,'Team');check(v.awayTeamId,'Team');if(v.homeTeamId===v.awayTeamId)throw Error('Choose two different teams.');const day=new Date(new Date(v.scheduledAt).getTime()+7200000).toISOString().slice(0,10);if(day<c.published_payload.startDate||day>c.published_payload.endDate)throw Error('Fixture must fall within competition dates.');if(v.fixtureStatus==='Scheduled'&&tables.sport_records.some(r=>r.id!==id&&r.kind==='Fixture'&&r.published_payload?.fixtureStatus==='Scheduled'&&r.published_payload.scheduledAt===v.scheduledAt&&[r.published_payload.homeTeamId,r.published_payload.awayTeamId].some(t=>[v.homeTeamId,v.awayTeamId].includes(t))))throw Error('A team already has a fixture at this time.');}
  if(kind==='Result'){if(Boolean(v.athleteId)===Boolean(v.teamId))throw Error('Choose exactly one athlete or team.');check(v.athleteId||v.teamId,v.athleteId?'Athlete':'Team');if(v.outcome==='Placed'&&!/^[1-9][0-9]*$/.test(v.position))throw Error('A positive placing is required.');if(v.outcome!=='Placed'&&v.position)throw Error('Only placed results can carry a ranking position.');if(v.resultDate<c.published_payload.startDate||v.resultDate>c.published_payload.endDate||v.resultDate>new Date().toISOString().slice(0,10))throw Error('Invalid result date.');if(tables.sport_records.some(r=>r.id!==id&&r.kind==='Result'&&r.published_payload&&r.status!=='Archived'&&['competitionId','athleteId','teamId','fixtureId'].every(k=>(r.published_payload[k]||'')===(v[k]||''))))throw Error('A result already exists for this participant.');}
 }
}
function project(r){const v=r.published_payload;let collection,payload;
 if(r.kind==='Athlete'){collection='players';if(v.consentPublic)payload={id:r.id,associationId:r.association_id,firstName:v.name,lastName:'',gender:v.gender,position:v.discipline,category:v.category,club:v.club,district:v.district,status:'Active',nationalTeam:false};}
 if(r.kind==='Competition'){collection='events';payload={id:r.id,associationId:r.association_id,name:v.name,type:v.discipline,category:v.category,level:v.level,startDate:v.startDate,endDate:v.endDate,venue:v.venue,description:v.description,status:'Approved'};}
 if(r.kind==='Result'){collection='results';const a=approved(v.athleteId||v.teamId,v.athleteId?'Athlete':'Team',r.association_id);const c=approved(v.competitionId,'Competition',r.association_id);payload={id:r.id,associationId:r.association_id,playerId:v.athleteId||null,eventId:v.competitionId,category:c.published_payload.category,position:v.position?Number(v.position):null,performance:v.mark,unit:v.unit,outcome:v.outcome,resultDate:v.resultDate,teamName:v.teamId?a.published_payload.name:!a.published_payload.consentPublic?'Private athlete':null,medal:v.medal||null};}
 tables.registry=tables.registry.filter(x=>!(x.collection===collection&&x.id===r.id));if(payload)tables.registry.push({collection,id:r.id,payload});
 if(['Athlete','Team'].includes(r.kind))tables.sport_records.filter(x=>x.kind==='Result'&&x.published_payload&&x.status!=='Archived'&&[x.published_payload.athleteId,x.published_payload.teamId].includes(r.id)).forEach(project);
}
function ranking(p){const output=[];for(const policy of tables.ranking_policies.filter(r=>p.role!=='association'||r.association_id===p.association_id)){
 const byAthlete=new Map();for(const r of tables.sport_records){const v=r.published_payload;if(r.kind!=='Result'||!v||r.status==='Archived'||v.outcome!=='Placed'||!v.athleteId)continue;const c=approved(v.competitionId,'Competition',r.association_id),a=approved(v.athleteId,'Athlete',r.association_id);if(!c||!a||c.published_payload.rankingPolicyId!==policy.id)continue;let row=byAthlete.get(a.id);if(!row){row={athlete:a,competitions:new Map()};byAthlete.set(a.id,row);}row.competitions.set(c.id,Math.max(row.competitions.get(c.id)||0,policy.placing_points[Number(v.position)-1]||0));}
 const rows=[...byAthlete].map(([id,r])=>{const scores=[...r.competitions.values()].sort((a,b)=>b-a);return {policy_id:policy.id,association_id:policy.association_id,policy_name:policy.name,discipline:policy.discipline,category:policy.category,season:policy.season,athlete_id:id,athlete_name:r.athlete.published_payload.name,total_points:scores.slice(0,policy.max_results).reduce((a,b)=>a+b,0),counted_results:Math.min(scores.length,policy.max_results),available_results:scores.length};}).sort((a,b)=>b.total_points-a.total_points||a.athlete_name.localeCompare(b.athlete_name));rows.forEach((r,i)=>r.rank=i&&r.total_points===rows[i-1].total_points?rows[i-1].rank:i+1);output.push(...rows);
 }return output;
}
db.rpc=async(action,args={})=>{
 const session=await db.auth.getSession(),p=tables.profiles.find(p=>p.id===session.data.session?.user.id),reviewer=p&&['admin','reviewer'].includes(p.role);
 if(action==='public_fixtures')return ok(tables.sport_records.filter(r=>r.kind==='Fixture'&&r.published_payload&&r.status!=='Archived').map(r=>{const v=r.published_payload;return {id:r.id,competition:approved(v.competitionId,'Competition',r.association_id)?.published_payload.name,homeTeam:approved(v.homeTeamId,'Team',r.association_id)?.published_payload.name,awayTeam:approved(v.awayTeamId,'Team',r.association_id)?.published_payload.name,scheduledAt:v.scheduledAt,venue:v.venue,stage:v.stage,status:v.fixtureStatus};}));
 if(!['save_sport_record','transition_sport_record','sport_rankings','create_ranking_policy'].includes(action)){
  if(action==='transition_submission'&&args.next_status==='Submitted'){const s=tables.submissions.find(s=>s.id===args.submission_id);if(s?.kind==='Award nomination'){if(tables.award_cycles.find(c=>c.year===Number(s.period))?.nomination_status!=='Open')return error('MNCS must open nominations for this awards year.');if(s.payload.athleteId){const a=approved(s.payload.athleteId,'Athlete',s.association_id);if(!a||a.published_payload.name!==s.payload.nomineeName||(a.published_payload.dateOfBirth||'')!==(s.payload.dateOfBirth||''))return error('Nominee must match approved athlete details.');}}}
  return oldRpc(action,args);
 }
 if(!p)return error('Sign in');
 try{
  if(action==='sport_rankings')return ok(ranking(p));
  if(action==='create_ranking_policy'){if(p.role!=='admin')throw Error('MNCS administrator required.');if(!args.points.length||args.points.some((v,i)=>!Number.isFinite(v)||v<0||(i&&v>args.points[i-1])))throw Error('Points must be descending nonnegative numbers.');const id=uid();tables.ranking_policies.push({id,association_id:args.owner_id,name:args.policy_name,discipline:args.sport_discipline,category:args.division,season:args.season_year,placing_points:args.points,max_results:args.count_limit});return ok(id);}
  if(action==='save_sport_record'){if(!['admin','association'].includes(p.role)||(p.role==='association'&&p.association_id!==args.owner_id))throw Error('Own association or administrator required.');let r=tables.sport_records.find(r=>r.id===args.record_id);if(args.record_id&&!r)throw Error('Record not found.');if(r&&(r.association_id!==args.owner_id||r.kind!==args.record_kind||!['Draft','Returned','Approved'].includes(r.status)))throw Error('Cannot edit this record.');validate(args.owner_id,args.record_kind,args.new_payload,args.record_id);if(!r){r={id:uid(),association_id:args.owner_id,kind:args.record_kind,history:[],created_at:new Date().toISOString()};tables.sport_records.push(r);}r.payload={...args.new_payload};r.status='Draft';r.updated_at=new Date().toISOString();r.history.push({action:'Draft saved',at:r.updated_at,actor:p.id});return ok(r.id);}
  const r=tables.sport_records.find(r=>r.id===args.record_id);if(!r)throw Error('Record not found.');const next=args.next_status;
  if(next==='Submitted'){if(!['admin','association'].includes(p.role)||(p.role==='association'&&p.association_id!==r.association_id)||!['Draft','Returned'].includes(r.status))throw Error('Cannot submit.');}
  else if(['Approved','Returned'].includes(next)){if(!reviewer||r.status!=='Submitted')throw Error('MNCS review required.');}
  else if(next==='Archived'){if(!reviewer)throw Error('MNCS reviewer required.');if(tables.sport_records.some(x=>x.id!==r.id&&x.status!=='Archived'&&['competitionId','athleteId','teamId','fixtureId','homeTeamId','awayTeamId'].some(k=>x.payload[k]===r.id||x.published_payload?.[k]===r.id)))throw Error('Archive dependent records first.');}else throw Error('Invalid action.');
  if(['Returned','Archived'].includes(next)&&!args.comment.trim())throw Error('Reason required.');if(['Submitted','Approved'].includes(next))validate(r.association_id,r.kind,r.payload,r.id);
  r.status=next;r.review_comment=args.comment;r.updated_at=new Date().toISOString();r.history.push({action:next,comment:args.comment,actor:p.id,at:r.updated_at});if(next==='Approved'){r.published_payload={...r.payload};project(r);}if(next==='Archived'){r.published_payload=null;tables.registry=tables.registry.filter(x=>x.id!==r.id);}return ok(null);
 }catch(e){return error(e.message);}
};
})();
