(() => {
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.MNCS_TOURNAMENTS={async mount(root,db,profile,records,scope){
 const host=document.createElement('section');host.className='tournament-desk';root.appendChild(host);
 const canManage=['admin','association'].includes(profile.role),competitions=records.filter(r=>r.kind==='Competition'&&r.published_payload&&r.status!=='Archived'&&(!scope||r.association_id===scope));
 const teamName=id=>records.find(r=>r.id===id)?.published_payload?.name||'Winner of previous match';
 try{
 const [tournaments,matches]=await Promise.all([window.MNCS_SPORTS.all(db,'tournaments'),window.MNCS_SPORTS.all(db,'tournament_matches')]);
 host.innerHTML=`<h3>Automatic tournament planner</h3><p>Choose a competition, select teams and generate the schedule. Round robin works with 2–32 teams. Knockout works with 2, 4, 8, 16 or 32; winners progress after you record the result.</p>${canManage?`<details><summary>Generate a tournament</summary><form id="tournament-form" class="sports-form"><label>Accepted competition<select name="competition" required><option value="">Choose competition</option>${competitions.map(c=>`<option value="${c.id}">${esc(c.published_payload.name)}</option>`).join('')}</select></label><label>Format<select name="format"><option>Round robin</option><option>Knockout</option></select></label><label>First fixture, Malawi time<input name="start" type="datetime-local" required></label><label>Minutes between fixtures<input name="gap" type="number" min="15" max="1440" value="60" required></label><label>Venue<input name="venue" maxlength="160" required></label><fieldset id="tournament-teams"><legend>Teams, in seed order</legend></fieldset><p>Seed order is the order shown below. Games are scheduled one after another at the selected venue. Choose an interval long enough for play and rest.</p><button>Generate fixtures</button><p id="tournament-notice" role="status"></p></form></details>`:''}<div>${tournaments.filter(t=>!scope||t.association_id===scope).map(t=>`<article class="sport-record-card"><h4>${esc(records.find(c=>c.id===t.competition_id)?.published_payload?.name||'Tournament')} · ${esc(t.format)}</h4><div class="overflow-x-auto"><table><thead><tr><th>Round</th><th>Fixture</th><th>Time</th><th>Winner / next step</th></tr></thead><tbody>${matches.filter(m=>m.tournament_id===t.id).sort((a,b)=>a.round-b.round||a.slot-b.slot).map(m=>`<tr><td>${m.round}</td><td>${esc(teamName(m.home_team))} vs ${esc(teamName(m.away_team))}</td><td>${esc(window.MNCS_SPORTS.formatTime(m.scheduled_at))}</td><td>${m.winner?esc(teamName(m.winner)):canManage&&t.format==='Knockout'&&m.home_team&&m.away_team?`<select aria-label="Winner for round ${m.round} match ${m.slot}" id="winner-${m.id}"><option value="">Choose winner</option><option value="${m.home_team}">${esc(teamName(m.home_team))}</option><option value="${m.away_team}">${esc(teamName(m.away_team))}</option></select><button data-advance-match="${m.id}">Advance winner</button>`:'Record results in Results'}</td></tr>`).join('')}</tbody></table></div></article>`).join('')||'<p>No generated tournaments yet.</p>'}</div><p id="tournament-action-notice" role="status"></p>`;
 const form=host.querySelector('#tournament-form');if(form){
 form.elements.competition.onchange=()=>{const c=competitions.find(c=>c.id===form.elements.competition.value);const v=c?.published_payload;const teams=records.filter(r=>r.kind==='Team'&&r.published_payload&&r.status!=='Archived'&&r.association_id===c?.association_id&&r.published_payload.discipline===v?.discipline&&r.published_payload.category===v?.category);host.querySelector('#tournament-teams').innerHTML='<legend>Select teams in the displayed seed order</legend>'+teams.map(t=>`<label><input type="checkbox" name="team" value="${t.id}">${esc(t.published_payload.name)}</label>`).join('');if(v){form.elements.start.value=v.startDate+'T09:00';form.elements.venue.value=v.venue||'';}};
 form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;try{const f=new FormData(form);const r=await db.rpc('generate_tournament',{competition:f.get('competition'),team_ids:f.getAll('team'),format_name:f.get('format'),first_start:new Date(f.get('start')+':00+02:00').toISOString(),minutes_between:Number(f.get('gap')),ground:f.get('venue')});if(r.error)throw r.error;await loadData();host.remove();await window.MNCS_TOURNAMENTS.mount(root,db,profile,await window.MNCS_SPORTS.all(db,'sport_records'),scope);}catch(err){host.querySelector('#tournament-notice').textContent=err.message;}finally{b.disabled=false;}};}
 host.querySelectorAll('[data-advance-match]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const r=await db.rpc('advance_tournament',{match_id:b.dataset.advanceMatch,winning_team:host.querySelector('#winner-'+b.dataset.advanceMatch).value});if(r.error)throw r.error;host.remove();await window.MNCS_TOURNAMENTS.mount(root,db,profile,await window.MNCS_SPORTS.all(db,'sport_records'),scope);}catch(err){host.querySelector('#tournament-action-notice').textContent=err.message;}finally{b.disabled=false;}});
 }catch(error){host.textContent='Tournament planner unavailable: '+error.message;}
}};
})();
