import test from 'node:test';
import assert from 'node:assert/strict';
import {handler,validateAccount,equalSecret} from '../netlify/functions/accounts.mjs';
const account={email:'person@example.org',password:'a-test-password-123',display_name:'Example Person',role:'association',association_id:'BUM'};
const env={SUPABASE_URL:'https://test.example.org',SUPABASE_SECRET_KEY:'server-only-test-key',SITE_ORIGIN:'https://site.example.org',MNCS_SETUP_CODE:'x'.repeat(40)};
const event=body=>({httpMethod:'POST',headers:{origin:env.SITE_ORIGIN,authorization:'Bearer test-user-token'},body:JSON.stringify(body)});
async function withMock(routes,run){const saved={...process.env},original=global.fetch;Object.assign(process.env,env);const calls=[];global.fetch=async(url,options={})=>{const path=new URL(url).pathname;calls.push({path,method:options.method||'GET',body:options.body?JSON.parse(options.body):null});const value=routes(path,options);if(value===undefined)throw Error('Unexpected mock path '+path);return new Response(JSON.stringify(value?.body??value),{status:value?.status??200});};try{await run(calls);}finally{global.fetch=original;for(const k of Object.keys(env))if(saved[k]===undefined)delete process.env[k];else process.env[k]=saved[k];}}
test('validation enforces passwords, association assignments and known roles',()=>{assert.throws(()=>validateAccount({...account,password:'1234'}));assert.throws(()=>validateAccount({...account,association_id:''}));assert.throws(()=>validateAccount({...account,role:'owner'}));assert.equal(validateAccount({...account,action:'bootstrap',role:'association'}).role,'admin');assert.equal(equalSecret('x'.repeat(40),'x'.repeat(40)),true);assert.equal(equalSecret('short','short'),false);});
test('anonymous and non-admin callers cannot create accounts',async()=>{await withMock(path=>path==='/auth/v1/user'?{id:'reviewer-id'}:path==='/rest/v1/profiles'?[{role:'reviewer'}]:undefined,async calls=>{let request=event({...account,action:'create-account'});delete request.headers.authorization;assert.equal((await handler(request)).statusCode,401);assert.equal((await handler(event({...account,action:'create-account'}))).statusCode,403);assert(!calls.some(c=>c.path==='/auth/v1/admin/users'));});});
test('admin creation checks registered association and creates matching profile',async()=>{await withMock(path=>({'/auth/v1/user':{id:'admin-id'},'/rest/v1/profiles':[{role:'admin'}],'/rest/v1/registry':[{id:'BUM'}],'/auth/v1/admin/users':{id:'new-user-id'}}[path]),async calls=>{const response=await handler(event({...account,action:'create-account'}));assert.equal(response.statusCode,201);const write=calls.find(c=>c.path==='/rest/v1/profiles'&&c.method==='POST');assert.equal(write.body.id,'new-user-id');assert.equal(write.body.association_id,'BUM');assert(!('password'in write.body));});});
test('initial setup needs the secret and an atomic available claim',async()=>{await withMock(path=>path==='/rest/v1/rpc/claim_initial_admin'?false:undefined,async calls=>{assert.equal((await handler(event({...account,action:'bootstrap',setup_code:'wrong'}))).statusCode,403);assert.equal(calls.length,0);assert.equal((await handler(event({...account,action:'bootstrap',setup_code:env.MNCS_SETUP_CODE}))).statusCode,409);assert(!calls.some(c=>c.path==='/auth/v1/admin/users'));});});
test('successful initial setup creates admin profile through completion transaction',async()=>{await withMock(path=>({'/rest/v1/rpc/claim_initial_admin':true,'/auth/v1/admin/users':{id:'first-admin'},'/rest/v1/rpc/complete_initial_admin':null}[path]),async calls=>{assert.equal((await handler(event({...account,action:'bootstrap',setup_code:env.MNCS_SETUP_CODE}))).statusCode,201);assert.equal(calls.find(c=>c.path.includes('complete_initial_admin')).body.user_id,'first-admin');});});
test('requests from other origins are rejected before privileged operations',async()=>{await withMock(()=>undefined,async calls=>{const request=event({...account,action:'create-account'});request.headers.origin='https://other.example.org';assert.equal((await handler(request)).statusCode,403);assert.equal(calls.length,0);});});
test('association service reports duplicate IDs without an unrelated email error',async()=>{
 await withMock(path=>path==='/auth/v1/user'?{id:'admin-id'}:path==='/rest/v1/profiles'?[{role:'admin'}]:path==='/rest/v1/registry'?{status:409,body:{code:'23505'}}:undefined,async()=>{
  const response=await handler(event({action:'create-association',id:'BUM',name:'Bowling Union of Malawi',sport:'Bowling',shortName:'BUM'}));
  assert.equal(response.statusCode,409);assert.match(JSON.parse(response.body).message,/association ID/);
 });
});
