const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
test('V1 awards screens wire category setup, judge ballots, audit and fan votes',{skip:!process.env.JSDOM_MODULE},async()=>{
 const {JSDOM}=require(process.env.JSDOM_MODULE),dom=new JSDOM('<main id="root"></main>',{url:'https://mncs.example',runScripts:'outside-only'}),w=dom.window,d=w.document;
 const category={id:'sportswoman',name:'Sportswoman',criteriaSummary:['Performance','Leadership']},config={year:2026,category:category.id,phase:'Preparing',rubric:[{label:'Performance',weight:60},{label:'Leadership',weight:40}],minimum_judges:1,poll_status:'Closed'};
 const nominee={id:'nom1',kind:'Award nomination',period:'2026',status:'Approved',association_id:'A',payload:{categoryId:category.id,nomineeName:'Thoko',description:'Athlete',motivation:'National championships winner'}};
 const candidate={id:'candidate1',year:2026,category:category.id,nomination_id:'nom1',nominee_name:'Thoko',association_id:'A'};
 const tables={award_categories:[config],award_candidates:[candidate],award_assignments:[{year:2026,category:category.id,user_id:'judge1',duty:'judge'},{year:2026,category:category.id,user_id:'audit1',duty:'auditor'}],award_ballots:[],award_audits:[],profiles:[{id:'judge2',role:'judge',display_name:'Judge Two'}],submissions:[nominee]};
 const calls=[];let publicRows=[],profile;
 const db={rpc:async(name,args)=>{calls.push({name,args});return {data:name==='public_awards'?publicRows:null,error:null};},from:()=>({select(){return this;},eq(){return this;},async maybeSingle(){return {data:nominee,error:null};}})};
 w.MNCS_SPORTS={all:async(_,name)=>tables[name]||[]};w.getAssociation=()=>({name:'Association A'});w.MNCS_SELECTED_AWARD=category.id;w.eval(fs.readFileSync('js/awards-desk.js','utf8'));
 const render=async()=>{d.querySelector('#root').innerHTML='';await w.MNCS_AWARDS_DESK.mount(d.querySelector('#root'),db,profile,[category],[{year:2026,nomination_status:'Open'}]);};w.renderAwards=render;
 const submit=async(selector,values)=>{const f=d.querySelector(selector);assert(f,selector);for(const [k,v] of Object.entries(values)){if(typeof v==='boolean')f.elements[k].checked=v;else f.elements[k].value=v;}f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));for(let i=0;i<5;i++)await new Promise(r=>setImmediate(r));};
 try{
 profile={id:'admin',role:'admin'};await render();await submit('#rubric-form',{'weight-0':60,'weight-1':40,quorum:1,approved:true});assert.deepEqual(JSON.parse(JSON.stringify(calls.find(c=>c.name==='configure_award_category').args)),{y:2026,c:'sportswoman',criteria:config.rubric,quorum:1});
 await submit('#official-assignment-form',{official:'judge2'});assert.equal(calls.find(c=>c.name==='assign_award_official').args.official_duty,'judge');
 config.phase='Judging';profile={id:'judge1',role:'judge'};await render();assert(!d.querySelector('#rubric-form'));await submit('[data-judge-form]',{'mark-0':9,'mark-1':8,reason:'Strong evidence across both criteria',conflict:true});const ballot=calls.find(c=>c.name==='submit_award_ballot');assert.deepEqual(Array.from(ballot.args.marks),[9,8]);assert.equal(ballot.args.no_conflict,true);d.querySelector('[data-dossier]').click();await new Promise(r=>setImmediate(r));assert.match(d.querySelector('.dossier-detail').textContent,/National championships/);
 config.phase='Auditing';tables.award_ballots=[{candidate_id:'candidate1',judge_id:'judge1',scores:[9,8],score:86,rationale:'Strong evidence'}];profile={id:'audit1',role:'auditor'};await render();assert.match(d.querySelector('table').textContent,/86.00/);await submit('#audit-certification-form',{statement:'I independently checked every ballot and recomputed the totals.'});assert(calls.find(c=>c.name==='certify_award'));
 publicRows=[{year:2026,category:'sportswoman',pollStatus:'Open',candidates:[{id:'candidate1',name:'Thoko',votes:null}],results:null}];profile={id:'fan1',role:'fan'};await render();assert(!d.querySelector('#official-category'));d.querySelector('[data-fan-vote]').click();await new Promise(r=>setImmediate(r));assert.equal(calls.find(c=>c.name==='cast_fan_vote').args.candidate,'candidate1');assert.match(d.querySelector('#fan-notice').textContent,/does not affect/);
 }finally{dom.window.close();}
});
