const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),{webcrypto}=require('node:crypto');
test('isolated demo runs account, association, reporting, document and junior nomination processes',async()=>{
 let fetches=0;const context={window:{},crypto:webcrypto,URL:{createObjectURL:()=> 'blob:demo'},console,fetch:async path=>{assert.equal(path,'data/researched-associations.json');fetches++;return {json:async()=>JSON.parse(fs.readFileSync('data/researched-associations.json','utf8'))};}};
 vm.createContext(context);vm.runInContext(fs.readFileSync('js/award-scoring.js','utf8'),context);vm.runInContext(fs.readFileSync('js/demo.js','utf8'),context);
 const db=context.window.MNCS_DEMO.db;await context.window.MNCS_DEMO.ready;
 const login=async role=>{const result=await db.auth.signInWithPassword({email:role+'@mncs.example',password:'1234'});assert.equal(result.error,null);};
 await login('admin');assert.equal((await db.from('registry').select('*')).data.length,30);
 await db.rpc('edit_association_basics',{association_key:'DEMO-ASSOC',association_name:'Edited Demo',abbreviation:'ED',sport_name:'Demo'});
 assert.equal((await db.from('registry').select('*').eq('id','DEMO-ASSOC').maybeSingle()).data.payload.name,'Edited Demo');
 const created=await db.demoAction({action:'create-account',email:'another@example.org',password:'1234',role:'association',association_id:'DEMO-ASSOC',display_name:'Pseudo account'});assert.match(created.message,/Demo account/);
 await db.from('reporting_requirements').insert({id:'r1',kind:'AGM minutes',period:'2026',due_date:'2026-12-01',association_id:'DEMO-ASSOC'});
 await db.from('award_cycles').upsert({year:2026,age_reference_date:'2026-12-31',official_ranking_enabled:false});
 await login('association');assert.equal((await db.from('profiles').select('*')).data.length,1);
 assert((await db.from('award_cycles').upsert({year:2027})).error);
 await assert.rejects(()=>db.demoAction({action:'reset-password',user_id:'admin',password:'1234'}),/administrator/);
 await db.storage.from('association-documents').upload('DEMO-ASSOC/test.pdf',{type:'application/pdf',size:10});
 const row={id:'s1',association_id:'DEMO-ASSOC',created_by:'association',kind:'AGM minutes',period:'2026',payload:{summary:'demo'},status:'Draft',history:[],document_path:'DEMO-ASSOC/test.pdf'};
 assert.equal((await db.from('submissions').insert(row)).error,null);
 assert.equal((await db.rpc('transition_submission',{submission_id:'s1',next_status:'Submitted',comment:''})).error,null);
 await login('reviewer');assert.equal((await db.rpc('transition_submission',{submission_id:'s1',next_status:'Returned',comment:'Please correct'})).error,null);
 await login('association');await db.rpc('edit_submission',{submission_id:'s1',new_payload:{summary:'corrected'},new_document_path:row.document_path});await db.rpc('transition_submission',{submission_id:'s1',next_status:'Submitted',comment:''});
 await login('reviewer');await db.rpc('transition_submission',{submission_id:'s1',next_status:'Approved',comment:'Reviewed'});
 assert.equal((await db.from('submissions').select('*').eq('id','s1').maybeSingle()).data.status,'Approved');
 await login('association');await db.from('submissions').insert({...row,id:'junior',kind:'Award nomination',status:'Draft',payload:{categoryId:'junior-male',dateOfBirth:'2006-01-01'}});
 assert((await db.rpc('transition_submission',{submission_id:'junior',next_status:'Submitted',comment:''})).error);
 await db.rpc('edit_submission',{submission_id:'junior',new_payload:{categoryId:'junior-male',dateOfBirth:'2008-01-01'},new_document_path:row.document_path});assert.equal((await db.rpc('transition_submission',{submission_id:'junior',next_status:'Submitted',comment:''})).error,null);
 await login('association');await db.from('submissions').insert({...row,id:'profile-update',kind:'Profile update',status:'Draft',payload:{president:'Pseudo President',email:'private@mncs.example',phone:'private'}});await db.rpc('transition_submission',{submission_id:'profile-update',next_status:'Submitted',comment:''});
 await login('reviewer');await db.rpc('transition_submission',{submission_id:'profile-update',next_status:'Approved',comment:'Reviewed'});const published=(await db.from('registry').select('*').eq('id','DEMO-ASSOC').maybeSingle()).data.payload;assert.equal(published.president,'Pseudo President');assert(!('email' in published));assert(!('phone' in published));
 await login('admin');await db.demoAction({action:'reset-password',user_id:'reviewer',password:'4321'});assert((await db.auth.signInWithPassword({email:'reviewer@mncs.example',password:'1234'})).error);assert.equal((await db.auth.signInWithPassword({email:'reviewer@mncs.example',password:'4321'})).error,null);
 assert.equal(fetches,1);assert.equal(context.window.MNCS_CONFIG.supabaseUrl,'demo-only');
});
