import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
test('V1.1 national exchange: scoped credentials, council review, retries and private dossiers',{skip:!process.env.PGLITE_MODULE},async t=>{
 const {PGlite}=await import(process.env.PGLITE_MODULE);const pg=new PGlite();
 await pg.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.user',true),'')::uuid$$;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);create function storage.foldername(text) returns text[] language sql immutable as $$select string_to_array($1,'/')$$;grant usage on schema public,auth to anon,authenticated,service_role;alter default privileges in schema public grant all on tables to anon,authenticated,service_role;`);
 const installer=fs.readFileSync('supabase/INSTALL_ALL.sql','utf8');await pg.exec(installer);await pg.exec(installer);
 const ids={admin:'10000000-0000-0000-0000-000000000001',reviewer:'10000000-0000-0000-0000-000000000002',association:'10000000-0000-0000-0000-000000000003',other:'10000000-0000-0000-0000-000000000004'};
 for(const [r,id] of Object.entries(ids)){await pg.query('insert into auth.users values($1,$2,now())',[id,r+'@example.org']);await pg.query('insert into profiles(id,role,association_id) values($1,$2,$3)',[id,['association','other'].includes(r)?'association':r,r==='association'?'TEST-A':r==='other'?'TEST-B':null]);}
 await pg.exec(`insert into registry values('associations','TEST-A','{"name":"Darts A","sport":"Darts"}'),('associations','TEST-B','{"name":"Other B","sport":"Other"}');`);
 const login=async r=>{await pg.exec('reset role');await pg.query("select set_config('test.user',$1,false)",[ids[r]||'']);await pg.exec('set role '+(r==='anon'?'anon':'authenticated'));};
 const call=async(n,args=[])=> (await pg.query('select * from public.'+n+'('+args.map((_,i)=>'$'+(i+1)).join(',')+')',args)).rows;
 let connection,comp,caseId;
 const receive=async message=>(await call('receive_association_message',[connection.connectorId,connection.token,message]))[0].receive_association_message;
 const competition=(revision,name='Regional darts')=>({kind:'Competition',externalId:'league:srdl:2026',revision,period:'2026',associationId:'TEST-B',payload:{name,startDate:'2026-05-01',endDate:'2026-12-01',discipline:'Darts',category:'Open',level:'Regional',phone:'DO-NOT-SHARE'}});
 await t.test('only MNCS admins issue scoped, hashed, one-time connection credentials',async()=>{await login('association');await assert.rejects(()=>call('configure_association_connector',['TEST-A','https://dartsmw.netlify.app','Darts']),/administrator/);await login('admin');await assert.rejects(()=>call('configure_association_connector',['TEST-A','javascript:alert(1)','Darts']),/HTTPS/);connection=(await call('configure_association_connector',['TEST-A','https://dartsmw.netlify.app','Darts']))[0].configure_association_connector;assert.equal(connection.token.length,64);assert(!JSON.stringify(await call('connector_status')).includes(connection.token));await assert.rejects(()=>pg.query('select token_hash from association_connectors'),/permission denied/);});
 await t.test('wrong keys fail; a valid key can write only its bound association',async()=>{await login('anon');await assert.rejects(()=>call('receive_association_message',[connection.connectorId,'0'.repeat(64),competition(1)]),/credentials/);comp=await receive(competition(1));await login('admin');const row=(await pg.query('select * from association_exchange where id=$1',[comp.id])).rows[0];assert.equal(row.association_id,'TEST-A');assert(!('phone' in row.payload));assert.equal((await pg.query("select * from registry where collection='events' and id=$1",['exchange-'+comp.id])).rows.length,0);});
 const summary={kind:'Performance summary',externalId:'league:srdl:2026:summary',revision:1,period:'2026',payload:{competitionExternalId:'league:srdl:2026',teams:4,athletes:8,fixtures:6,completedFixtures:2,publicConsent:false,leaders:[]}};
 await t.test('performance waits for competition acceptance; association cannot self-approve',async()=>{await login('anon');await assert.rejects(()=>receive(summary),/council acceptance/);await login('association');await assert.rejects(()=>call('review_shared_competition',[comp.id,'Approved','',1]),/reviewer/);await login('reviewer');await call('review_shared_competition',[comp.id,'Approved','Accepted',1]);const event=(await pg.query("select payload from registry where collection='events' and id=$1",['exchange-'+comp.id])).rows[0].payload;assert.equal(event.name,'Regional darts');assert.equal(event.sourceUrl,'https://dartsmw.netlify.app');});
 await t.test('retries are idempotent; stale or conflicting corrections fail without altering published records',async()=>{await login('anon');assert.equal((await receive(competition(1))).duplicate,true);await assert.rejects(()=>receive(competition(1,'Changed')),/Revision conflict/);await receive(competition(2,'Revised darts'));await login('reviewer');await assert.rejects(()=>call('review_shared_competition',[comp.id,'Approved','Stale screen',1]),/latest revision/);assert.equal((await pg.query("select payload->>'name' name from registry where id=$1",['exchange-'+comp.id])).rows[0].name,'Regional darts');await assert.rejects(()=>call('review_shared_competition',[comp.id,'Returned','',2]),/valid decision/);await call('review_shared_competition',[comp.id,'Returned','Clarify venue',2]);await login('anon');let receipts=await call('integration_receipts',[connection.connectorId,connection.token]);assert.equal(receipts[0].integration_receipts.status,'Returned');await receive(competition(3,'Revised darts'));await login('reviewer');await call('review_shared_competition',[comp.id,'Approved','Accepted revision',3]);});
 await t.test('public summaries are allowlisted; named leaders require explicit permission',async()=>{await login('anon');await assert.rejects(()=>receive({...summary,payload:{...summary.payload,leaders:[{name:'Thoko',rank:1}],publicConsent:null}}),/permission/);await receive({...summary,payload:{...summary.payload,email:'DO-NOT-SHARE'}});const publicRows=await call('public_performance_summaries');assert.equal(publicRows.length,1);assert(!JSON.stringify(publicRows).includes('DO-NOT-SHARE'));await receive({...summary,revision:2,payload:{...summary.payload,publicConsent:true,leaders:[{name:'Thoko',rank:1,singlesWins:4,dateOfBirth:'PRIVATE'}]}});assert(!JSON.stringify(await call('public_performance_summaries')).includes('PRIVATE'));});
 await t.test('reports and nominations arrive as private drafts, not approved awards entries',async()=>{await login('anon');caseId=(await receive({kind:'Funding request',externalId:'grant-1',revision:1,period:'2026',payload:{title:'Tournament travel',summary:'Transport support',requestedAmount:'120000',currency:'MWK'}})).id;await receive({kind:'Annual report',externalId:'report-2026',revision:1,period:'2026',payload:{title:'Annual report',summary:'Activities and performance'}});await receive({kind:'Award nomination',externalId:'junior-1',revision:1,period:'2026',payload:{categoryId:'junior-female',nomineeName:'Thoko',dateOfBirth:'2008-01-01',description:'Darts athlete',motivation:'National achievements'}});assert(!JSON.stringify(await call('public_performance_summaries')).includes('2008-01-01'));await login('other');assert.equal((await pg.query('select * from association_exchange')).rows.length,0);await login('association');assert.equal((await pg.query('select * from submissions')).rows.length,1);await assert.rejects(()=>pg.query("insert into submissions(association_id,created_by,kind,period,payload) values('TEST-A',$1,'Annual report','2026','{}')",[ids.association]),/row-level security/);});
 await t.test('requests submit directly; source corrections and council decisions return through receipts',async()=>{await login('association');const payload={title:'Tournament travel',summary:'Transport support',requestedAmount:'120000',currency:'MWK',sourceIntegrationId:caseId};const id=(await pg.query('select submission_id from association_exchange where id=$1',[caseId])).rows[0].submission_id;assert(id);assert.equal((await pg.query('select status from submissions where id=$1',[id])).rows[0].status,'Submitted');await assert.rejects(()=>pg.query("insert into submissions(association_id,created_by,kind,period,payload) values('TEST-A',$1,'Funding request','2026',$2)",[ids.association,payload]),/only one dossier/);await login('anon');await assert.rejects(()=>receive({kind:'Funding request',externalId:'grant-1',revision:2,period:'2026',payload:{...payload,requestedAmount:'150000'}}),/with council/);await login('reviewer');await call('transition_submission',[id,'Returned','Provide transport details']);await login('association');await assert.rejects(()=>call('edit_submission',[id,{...payload,sourceIntegrationId:''},null]),/retains its source/);await login('anon');await receive({kind:'Funding request',externalId:'grant-1',revision:2,period:'2026',payload:{...payload,requestedAmount:'150000',summary:'Vehicle hire details supplied'}});await login('reviewer');assert.equal((await pg.query('select status from submissions where id=$1',[id])).rows[0].status,'Submitted');await call('transition_submission',[id,'Approved','Granted']);await login('anon');const r=(await call('integration_receipts',[connection.connectorId,connection.token])).map(r=>r.integration_receipts).find(r=>r.id===caseId);assert.equal(r.status,'Approved');assert.equal(r.submissionId,id);assert.equal(r.comment,'Granted');});
 await t.test('pausing and rotating credentials revoke access and preserve receipt history',async()=>{await login('admin');await call('set_connector_enabled',[connection.connectorId,false]);await login('anon');await assert.rejects(()=>call('integration_receipts',[connection.connectorId,connection.token]),/credentials/);const old=connection;await login('admin');connection=(await call('configure_association_connector',['TEST-A','https://dartsmw.netlify.app','Darts']))[0].configure_association_connector;assert.equal(connection.connectorId,old.connectorId);await login('anon');await assert.rejects(()=>call('integration_receipts',[old.connectorId,old.token]),/credentials/);assert((await call('integration_receipts',[connection.connectorId,connection.token])).length>=5);await pg.exec('reset role');await pg.exec(installer);assert((await pg.query('select * from association_exchange')).rows.length>=5);});
 await pg.close();
});
