import test from 'node:test';import assert from 'node:assert/strict';
import {handler as gateway} from '../netlify/functions/association-gateway.mjs';
import {handler as darts} from '../integrations/darts/netlify/functions/mncs-connect.mjs';
import {leagueSummary} from '../integrations/darts/lib/mncs-adapter.mjs';
const id='10000000-0000-0000-0000-000000000001',token='a'.repeat(64);
const event=body=>({httpMethod:'POST',headers:{origin:'https://dartsmw.netlify.app'},body:JSON.stringify(body)});
async function mocked(routes,run){const original=global.fetch,names=['SUPABASE_URL','SUPABASE_SECRET_KEY','MNCS_CONNECTOR_ID','MNCS_CONNECTOR_TOKEN'],saved=Object.fromEntries(names.map(n=>[n,process.env[n]]));Object.assign(process.env,{SUPABASE_URL:'https://supabase.example',SUPABASE_SECRET_KEY:'server-key',MNCS_CONNECTOR_ID:id,MNCS_CONNECTOR_TOKEN:token});const calls=[];global.fetch=async(url,opts={})=>{const body=opts.body?JSON.parse(opts.body):null;calls.push({url:String(url),opts,body});const reply=routes(String(url),opts,body);assert(reply,'Unexpected network destination');return new Response(JSON.stringify(reply.data),{status:reply.status||200});};try{await run(calls);}finally{global.fetch=original;for(const n of names)if(saved[n]===undefined)delete process.env[n];else process.env[n]=saved[n];}}
test('MNCS gateway bounds requests and forwards only guarded RPC arguments',async()=>{assert.equal((await gateway({...event({}),httpMethod:'GET'})).statusCode,405);assert.equal((await gateway(event({connectorId:id,token,action:'unknown'}))).statusCode,400);await mocked(()=>({data:{id:'receipt',revision:1}}),async calls=>{const res=await gateway(event({action:'send',connectorId:id,token,message:{kind:'Competition'},associationId:'OTHER'}));assert.equal(res.statusCode,200);assert.equal(calls[0].url,'https://supabase.example/rest/v1/rpc/receive_association_message');assert.equal(calls[0].body.connector,id);assert(!('associationId' in calls[0].body));assert(!res.body.includes(token));});});
test('gateway reports revoked keys and revision conflicts without exposing credentials',async()=>{await mocked(()=>({status:400,data:{message:'Integration credentials invalid or disabled'}}),async()=>assert.equal((await gateway(event({action:'receipts',connectorId:id,token}))).statusCode,401));await mocked(()=>({status:400,data:{message:'Revision conflict; refresh receipts before retrying'}}),async()=>assert.equal((await gateway(event({action:'send',connectorId:id,token,message:{}}))).statusCode,409));});
test('Darts connector rejects other origins and captains; it rechecks existing server authority',async()=>{assert.equal((await darts({...event({}),headers:{origin:'https://evil.example'}})).statusCode,403);await mocked(()=>({data:{role:'captain'}}),async calls=>{const res=await darts(event({action:'receipts',region:'srdl',password:'test-password'}));assert.equal(res.statusCode,403);assert.equal(calls.length,1);assert.equal(calls[0].body.action,'login');});});
test('Darts committee receipts use server-only credentials and do not return keys',async()=>{await mocked(url=>url.includes('/results')?{data:{role:'admin',region:'srdl'}}:{data:{data:[{id:'r',status:'Approved'}]}},async calls=>{const res=await darts(event({action:'receipts',region:'srdl',password:'test-password'}));assert.equal(res.statusCode,200);assert(!res.body.includes(token));assert.equal(calls[1].body.token,token);assert(!('password' in calls[1].body));});});
const published={results:{one:{h:5,a:4,sheet:{singles:[{hp:'Thoko',ap:'Mphatso',hs:2,as:1,h180:1}],doubles:[]}},blank:{h:'',a:'',sheet:{}}},teams:{A:{name:'Club A',officials:[{contact:'PRIVATE'}]},B:{name:'Club B'}},pending:{fake:{h:9,a:0}}};
test('server summaries use published results, omit private contacts and hide names by default',()=>{const s=leagueSummary(published,4);assert.equal(s.completedFixtures,1);assert.equal(s.athletes,2);assert.equal(s.teams,2);assert.deepEqual(s.leaders,[]);assert(!JSON.stringify(s).includes('PRIVATE'));const named=leagueSummary(published,4,true);assert.equal(named.leaders[0].name,'Thoko');assert.equal(named.leaders[0].singlesWins,1);assert.equal(named.leaders[0].c180,1);});
test('sharing derives performance on the server and uses the next receipt revision',async()=>{await mocked((url,opts,body)=>{if(url.includes('/results'))return {data:opts.method==='POST'?{role:'admin'}:published};if(body.action==='receipts')return {data:{data:[{kind:'Performance summary',externalId:'summary',revision:3}]}};return {data:{data:{id:'m',revision:4}}};},async calls=>{const res=await darts(event({action:'send',region:'srdl',password:'test-password',fixtureCount:4,shareNames:false,message:{kind:'Performance summary',externalId:'summary',period:'2026',payload:{competitionExternalId:'league:srdl:2026',teams:99999,leaders:[{name:'Forged',rank:1}]}}}));assert.equal(res.statusCode,200);const send=calls.find(c=>c.body?.action==='send');assert.equal(send.body.message.revision,4);assert.equal(send.body.message.payload.teams,2);assert.equal(send.body.message.payload.completedFixtures,1);assert.deepEqual(send.body.message.payload.leaders,[]);assert(!JSON.stringify(send.body).includes('test-password'));});});
test('Darts pilot refuses relabelling current 2026 results as another season',async()=>{await mocked(()=>({data:{role:'admin'}}),async calls=>{assert.equal((await darts(event({action:'send',region:'srdl',password:'test-password',message:{kind:'Performance summary',period:'2027'}}))).statusCode,400);assert.equal(calls.length,1);});});
test('gateway supports Supabase secret keys without sending them as JWT bearer tokens',async()=>{await mocked(()=>({data:[]}),async calls=>{process.env.SUPABASE_SECRET_KEY='sb_secret_test_server_only';const r=await gateway(event({action:'receipts',connectorId:id,token}));assert.equal(r.statusCode,200);assert.equal(calls[0].opts.headers.apikey,'sb_secret_test_server_only');assert(!('Authorization' in calls[0].opts.headers));});});
