const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{webcrypto}=require('node:crypto');
test('national workspace replaces daily operations and completes imported requests and nominations',{skip:!process.env.JSDOM_MODULE},async()=>{
 const {JSDOM}=require(process.env.JSDOM_MODULE),dom=new JSDOM(fs.readFileSync('demo.html','utf8'),{url:'https://mncs-demo.example/demo.html',runScripts:'outside-only'}),w=dom.window,d=w.document;
 Object.defineProperty(w,'crypto',{value:webcrypto});w.fetch=async path=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path,'utf8'))});w.URL.createObjectURL=()=> 'blob:demo';w.URL.revokeObjectURL=()=>{};
 const settle=async()=>{for(let i=0;i<15;i++)await new Promise(r=>setImmediate(r));};const submit=s=>d.querySelector(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));const click=s=>{assert(d.querySelector(s),s);d.querySelector(s).click();};
 w.eval(['demo','demo-sports','demo-awards'].map(f=>fs.readFileSync('js/'+f+'.js','utf8')).join('\n'));const tables=w.MNCS_DEMO.tables,call=w.MNCS_DEMO.db.rpc.bind(w.MNCS_DEMO.db),calls=[];
 const base={association_id:'DEMO-ASSOC',connector_id:'connector1',source_url:'https://dartsmw.netlify.app',period:'2026',revision:1,history:[],updated_at:'2026-10-02T18:00:00Z'};
 tables.association_exchange=[{...base,id:'comp1',kind:'Competition',external_id:'league:srdl:2026',status:'Submitted',payload:{name:'Regional darts',startDate:'2026-05-01',endDate:'2026-12-01',venue:'Blantyre'}},{...base,id:'fund1',kind:'Annual report',external_id:'report',status:'Ready to complete',payload:{title:'Annual activities',summary:'League and national activities'}},{...base,id:'nom1',kind:'Award nomination',external_id:'nom',status:'Ready to complete',payload:{categoryId:'junior-female',nomineeName:'Thoko Banda',dateOfBirth:'2008-01-01',description:'Darts athlete',motivation:'Strong league performances'}}];
 w.MNCS_DEMO.db.rpc=async(name,args)=>{calls.push({name,args});if(name==='connector_status')return {data:[{id:'connector1',association_id:'DEMO-ASSOC',name:'Darts Malawi',site_url:'https://dartsmw.netlify.app',enabled:true,last_received_at:'2026-10-02T18:00:00Z'}],error:null};if(name==='review_shared_competition'){tables.association_exchange[0].status=args.decision;return {data:null,error:null};}return call(name,args);};
 w.eval(['app','reporting','accounts','award-scoring','awards','tournaments','awards-desk','sports','integration','portal'].map(f=>fs.readFileSync('js/'+f+'.js','utf8')).join('\n'));
 try{
 await settle();w.switchView('portal');click('[data-demo-login="admin"]');await settle();assert(!d.querySelector('[data-panel="sports"]'));assert(!d.querySelector('[data-panel="rankings"]'));assert(d.querySelector('[data-panel="connections"]'));assert(d.querySelector('[data-panel="performance"]'));click('[data-panel="connections"]');assert.match(d.querySelector('#workspace-connections').textContent,/Data received/);assert.equal(d.querySelector('#workspace-connections a').getAttribute('href'),'https://dartsmw.netlify.app/');
 click('[data-panel="competitions"]');click('[data-shared-review="comp1"][data-decision="Approved"]');await settle();assert.equal(calls.find(c=>c.name==='review_shared_competition').args.expected_revision,1);
 click('#logout');await settle();click('[data-demo-login="association"]');await settle();click('[data-panel="exchange"]');click('[data-complete-exchange="fund1"]');assert.equal(d.querySelector('#workspace-submissions').hidden,false);let form=d.querySelector('#submission-form');assert.equal(form.elements.kind.value,'Annual report');assert.equal(form.elements.summary.value,'League and national activities');assert(!form.elements.president);const reportFile=new w.File(['%PDF-demo'],'report.pdf',{type:'application/pdf'}),ReportBase=w.FormData;w.FormData=class extends ReportBase{get(k){return k==='document'?reportFile:super.get(k);}};submit('#submission-form');await settle();const fund=tables.submissions.find(s=>s.kind==='Annual report');assert.equal(fund.payload.sourceIntegrationId,'fund1');
 click('[data-panel="exchange"]');click('[data-complete-exchange="nom1"]');await settle();form=d.querySelector('#award-nomination-form');assert.equal(form.hidden,false);assert.equal(form.elements.category.value,'junior-female');assert.equal(form.elements.nomineeName.value,'Thoko Banda');assert.equal(form.elements.dateOfBirth.value,'2008-01-01');assert.equal(form.elements.dateOfBirth.required,true);form.elements.declaration.checked=true;const file=new w.File(['%PDF-demo'],'evidence.pdf',{type:'application/pdf'}),Base=w.FormData;w.FormData=class extends Base{get(k){return k==='document'?file:super.get(k);}};submit('#award-nomination-form');await settle();const nom=tables.submissions.find(s=>s.kind==='Award nomination');assert.equal(nom.payload.sourceIntegrationId,'nom1');assert.equal(nom.status,'Draft');
 }finally{dom.window.close();}
});

test('Darts addon sends competitions, defaults summaries to anonymous and preselects nomination categories',{skip:!process.env.JSDOM_MODULE},async()=>{
 const {JSDOM}=require(process.env.JSDOM_MODULE),dom=new JSDOM('<nav id="siteNav"><button data-s="home">Home</button></nav><main><section id="home" class="active">Existing Darts home</section></main>',{url:'https://dartsmw.netlify.app',runScripts:'outside-only'}),w=dom.window,d=w.document;Object.defineProperty(w,'crypto',{value:webcrypto});const sent=[];
 w.activeDataRegion=()=> 'srdl';w.getAdminPass=()=> 'test-committee';w.FX=[{id:'R1',h:'A',a:'B',d:'2026-05-01'},{id:'R2',h:'B',a:'A',d:'2026-12-01'}];w.userCompetitions=[];
 w.fetch=async(url,opts={})=>{if(!opts.body)return {ok:true,json:async()=>JSON.parse(fs.readFileSync('data/award-categories.json','utf8'))};const body=JSON.parse(opts.body);sent.push(body);return {ok:true,json:async()=>({data:body.action==='receipts'?[]:body.action==='preview'?{teams:2,athletes:2,completedFixtures:1,rankingRule:'Saved league results',leaders:body.shareNames?[{name:'Thoko',rank:1,singlesWins:2,doublesWins:1,legDifference:3,c180:1}]:[]}:{id:'receipt'}})};};
 w.eval(fs.readFileSync('integrations/darts/assets/mncs-connect.js','utf8'));const settle=async()=>{for(let i=0;i<6;i++)await new Promise(r=>setImmediate(r));};const submit=s=>d.querySelector(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 try{d.querySelector('[data-s="mncs-exchange"]').click();await settle();assert(d.querySelector('#home'));assert.equal(d.querySelector('#home').classList.contains('active'),false);assert.equal(d.querySelector('#mncs-competition-form').elements.startDate.value,'2026-05-01');submit('#mncs-competition-form');await settle();assert.equal(sent.find(x=>x.action==='send').message.externalId,'league:srdl:2026');assert(!d.querySelector('#mncs-summary-form').elements.shareNames.checked);submit('#mncs-summary-form');await settle();assert.equal(sent.filter(x=>x.action==='send')[1].shareNames,false);const f=d.querySelector('#mncs-case-form');f.elements.kind.value='Award nomination';f.elements.kind.dispatchEvent(new w.Event('change'));d.querySelector('[data-mncs-category="junior-female"]').click();assert.equal(f.elements.categoryId.value,'junior-female');assert.equal(f.elements.dateOfBirth.required,true);d.querySelector('#mncs-load-athlete').click();await settle();d.querySelector('#mncs-athlete').value='0';d.querySelector('#mncs-athlete').dispatchEvent(new w.Event('change'));assert.equal(f.elements.nomineeName.value,'Thoko');assert.match(f.elements.motivation.value,/2 singles wins/);}finally{dom.window.close();}
});
