const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{webcrypto}=require('node:crypto');
test('V1.0 workspace UI saves association records directly, reviews competitions and preselects nominations',{skip:!process.env.JSDOM_MODULE},async()=>{
 const {JSDOM}=require(process.env.JSDOM_MODULE);
 const dom=new JSDOM(fs.readFileSync('demo.html','utf8'),{url:'https://mncs-demo.example/demo.html',runScripts:'outside-only'}),w=dom.window,d=w.document;
 Object.defineProperty(w,'crypto',{value:webcrypto});w.fetch=async path=>{assert(!String(path).startsWith('http'));return {ok:true,json:async()=>JSON.parse(fs.readFileSync(path,'utf8'))};};
 w.URL.createObjectURL=()=> 'blob:demo';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){w.lastDownload=this.download;};
 const settle=async()=>{for(let i=0;i<10;i++)await new Promise(r=>setImmediate(r));};
 w.eval(['demo','demo-sports','demo-awards','app','reporting','accounts','award-scoring','awards','tournaments','awards-desk','sports','portal'].map(file=>fs.readFileSync('js/'+file+'.js','utf8')).join('\n'));
 const click=selector=>{assert(d.querySelector(selector),'Missing '+selector);d.querySelector(selector).click();};
 const submit=selector=>d.querySelector(selector).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 const setFields=(selector,values)=>{const form=d.querySelector(selector);for(const [k,v] of Object.entries(values)){assert(form.elements[k],'Missing field '+k);form.elements[k].value=String(v);}return form;};
 async function login(role){w.switchView('portal');if(d.querySelector('#logout')){click('#logout');await settle();}click('[data-demo-login="'+role+'"]');await settle();}
 try{
  await settle();await login('admin');for(const id of ['sports','rankings','security']){click('[data-panel="'+id+'"]');assert.equal(d.querySelector('#workspace-'+id).hidden,false);}
  setFields('#ranking-policy-form',{association:'DEMO-ASSOC',name:'Demo running rule',discipline:'100 m',category:'Senior women',season:2026,points:'10,8,6',maxResults:2});submit('#ranking-policy-form');await settle();const policy=w.MNCS_DEMO.tables.ranking_policies[0];assert(policy);
  await login('association');click('[data-panel="sports"]');
  setFields('#sport-record-form',{name:'Thoko Banda',discipline:'100 m',category:'Senior women',gender:'Female',dateOfBirth:'2008-01-01',consentPublic:'true'});submit('#sport-record-form');await settle();const athlete=w.MNCS_DEMO.tables.sport_records[0];assert.equal(athlete.status,'Approved');assert.equal(d.querySelector('#account-identity').hidden,false);
  assert.equal(athlete.status,'Approved');assert.equal(d.querySelector('#stat-players').textContent,'1');
  await login('association');click('[data-panel="sports"]');click('[data-sport-kind="Competition"]');
  setFields('#sport-record-form',{name:'Demo championships',discipline:'100 m',category:'Senior women',season:2026,startDate:'2026-01-01',endDate:'2026-12-31',level:'National',rankingPolicyId:policy.id,venue:'Demo stadium'});submit('#sport-record-form');await settle();const competition=w.MNCS_DEMO.tables.sport_records.find(r=>r.kind==='Competition');assert(competition);click('[data-sport-transition="'+competition.id+'"][data-next="Submitted"]');await settle();
  await login('reviewer');click('[data-panel="sports"]');click('[data-sport-kind="Competition"]');click('[data-sport-transition="'+competition.id+'"][data-next="Approved"]');await settle();
  await login('association');click('[data-panel="sports"]');click('[data-sport-kind="Result"]');setFields('#sport-record-form',{competitionId:competition.id,athleteId:athlete.id,resultDate:'2026-09-01',outcome:'Placed',position:1,mark:'12.00',unit:'s',evidenceNote:'Signed result sheet'});submit('#sport-record-form');await settle();const result=w.MNCS_DEMO.tables.sport_records.find(r=>r.kind==='Result');assert(result);assert.equal(result.status,'Approved');
  click('[data-panel="rankings"]');assert.match(d.querySelector('#ranking-table').textContent,/Thoko Banda/);assert.match(d.querySelector('#ranking-table').textContent,/10/);click('#ranking-export');assert.equal(w.lastDownload,'MNCS-athlete-rankings.csv');
  await login('association');click('[data-panel="sports"]');click('[data-sport-kind="Team"]');
  for(const name of ['Demo team A','Demo team B']){setFields('#sport-record-form',{name,discipline:'100 m',category:'Senior women'});submit('#sport-record-form');await settle();const team=w.MNCS_DEMO.tables.sport_records.find(r=>r.kind==='Team'&&r.payload.name===name);assert(team);assert.equal(team.status,'Approved');}
  await login('association');click('[data-panel="sports"]');click('[data-sport-kind="Fixture"]');const teams=w.MNCS_DEMO.tables.sport_records.filter(r=>r.kind==='Team');setFields('#sport-record-form',{competitionId:competition.id,homeTeamId:teams[0].id,awayTeamId:teams[1].id,scheduledAt:'2026-10-01T10:00',venue:'Demo stadium',stage:'Final',fixtureStatus:'Scheduled'});submit('#sport-record-form');await settle();const fixture=w.MNCS_DEMO.tables.sport_records.find(r=>r.kind==='Fixture');assert(fixture);assert.equal(fixture.payload.scheduledAt,'2026-10-01T08:00:00.000Z');assert.equal(fixture.status,'Approved');
  w.switchView('events');await settle();assert.match(d.querySelector('#public-fixtures').textContent,/Demo team A vs Demo team B/);assert.match(d.querySelector('#public-fixtures').textContent,/10:00 CAT/);
  await login('admin');w.switchView('awards');await settle();const cycleForm=setFields('#award-cycle-form',{year:2026,referenceDate:'2026-12-31',nominationStatus:'Open',scoringPolicy:'judges_only'});cycleForm.elements.approved.checked=true;cycleForm.elements.disclosed.checked=true;submit('#award-cycle-form');await settle();assert.equal(w.MNCS_DEMO.tables.award_cycles[0].nomination_status,'Open');
  await login('association');click('[data-panel="rankings"]');click('[data-rank-nominate="'+athlete.id+'"]');await settle();const nomination=d.querySelector('#award-nomination-form');assert(nomination);assert.equal(nomination.elements.nomineeName.value,'Thoko Banda');assert.equal(nomination.elements.dateOfBirth.value,'2008-01-01');assert.match(nomination.elements.motivation.value,/Demo championships/);assert.match(nomination.elements.motivation.value,/Result record/);
  click('[data-award-category="junior-female"]');await settle();assert.equal(nomination.elements.category.value,'junior-female');assert.equal(nomination.elements.dateOfBirth.required,true);nomination.elements.declaration.checked=true;
  const file=new w.File(['%PDF-demo'],'evidence.pdf',{type:'application/pdf'});const BaseFormData=w.FormData;w.FormData=class extends BaseFormData{get(k){return k==='document'?file:super.get(k);}};
  submit('#award-nomination-form');await settle();const dossier=w.MNCS_DEMO.tables.submissions.find(s=>s.kind==='Award nomination');assert(dossier);assert.equal(dossier.payload.athleteId,athlete.id);assert.equal(dossier.status,'Draft');
  w.switchView('portal');click('[data-panel="submissions"]');click('[data-submit="'+dossier.id+'"]');await settle();assert.equal(dossier.status,'Submitted');
  w.switchView('portal');click('[data-panel="submissions"]');const request=d.querySelector('#submission-form');request.elements.kind.value='Funding request';request.elements.kind.dispatchEvent(new w.Event('change'));assert(!request.elements.president);setFields('#submission-form',{title:'National tournament grant',summary:'Request for tournament transport',requestedAmount:100000,currency:'MWK'});submit('#submission-form');await settle();assert(w.MNCS_DEMO.tables.submissions.some(s=>s.kind==='Funding request'&&s.payload.title==='National tournament grant'));
  w.switchView('events');await settle();assert.match(d.querySelector('#public-fixtures').textContent,/Demo team A vs Demo team B/);
 }finally{dom.window.close();}
});
