import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const path=process.env.PGLITE_MODULE;
test('V1 association ownership, council requests, tournaments and independent awards',{skip:!path},async t=>{
 const {PGlite}=await import(path);const pg=new PGlite();await pg.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.user',true),'')::uuid$$;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);create function storage.foldername(text) returns text[] language sql immutable as $$select string_to_array($1,'/')$$;grant usage on schema public,auth to anon,authenticated,service_role;alter default privileges in schema public grant all on tables to anon,authenticated,service_role;`);
 const installer=fs.readFileSync('supabase/INSTALL_ALL.sql','utf8');await pg.exec(installer);await pg.exec(installer);
 const ids={};for(const [i,role] of ['admin','reviewer','association','other','judge','judge2','auditor','fan','unverified'].entries()){const id='10000000-0000-0000-0000-'+String(i+1).padStart(12,'0');ids[role]=id;await pg.query('insert into auth.users values($1,$2,$3)',[id,role+'@example.org',role==='unverified'?null:'2026-01-01']);if(role!=='unverified')await pg.query('insert into profiles(id,role,association_id) values($1,$2,$3)',[id,role==='other'?'association':role==='judge2'?'judge':role,['association','other'].includes(role)?role==='other'?'TEST-B':'TEST-A':null]);}
 await pg.exec(`insert into registry values('associations','TEST-A','{"name":"Test A","sport":"Bowls"}'),('associations','TEST-B','{"name":"Test B","sport":"Bowls"}');`);
 const login=async r=>{await pg.exec('reset role');await pg.query("select set_config('test.user',$1,false)",[ids[r]||'']);await pg.exec('set role '+(r==='anon'?'anon':'authenticated'));};
 const call=async(name,args=[])=> (await pg.query('select * from public.'+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+')',args)).rows;
 const save=async(kind,v,id=null)=> (await call('save_sport_record',[id,'TEST-A',kind,v]))[0].save_sport_record;
 let athlete,competition,policy,teams=[],tourney,nominees=[];
 await t.test('association saves players and teams immediately; only competitions require council approval',async()=>{await login('association');athlete=await save('Athlete',{name:'Thoko Banda',discipline:'Bowls',category:'Open',gender:'Female',consentPublic:true,dateOfBirth:'2008-01-01'});assert.equal((await pg.query('select status from sport_records where id=$1',[athlete])).rows[0].status,'Approved');for(let i=0;i<4;i++)teams.push(await save('Team',{name:'Team '+i,discipline:'Bowls',category:'Open'}));policy=(await call('create_ranking_policy',['TEST-A','Association rule','Bowls','Open',2026,[10,8,6],3]))[0].create_ranking_policy;competition=await save('Competition',{name:'National bowls','discipline':'Bowls',category:'Open',season:'2026',startDate:'2026-01-01',endDate:'2026-12-31',level:'National',rankingPolicyId:policy});assert.equal((await pg.query('select status from sport_records where id=$1',[competition])).rows[0].status,'Draft');await call('transition_sport_record',[competition,'Submitted','']);await assert.rejects(()=>call('transition_sport_record',[competition,'Approved','']),/MNCS review/);await login('reviewer');await call('transition_sport_record',[competition,'Approved','Accepted']);await assert.rejects(()=>call('transition_sport_record',[athlete,'Archived','Remove']),/reviewer required/);await login('other');assert.equal((await pg.query('select * from sport_records')).rows.length,0);});
 await t.test('association-owned results publish and rank without council errands',async()=>{await login('association');const r=await save('Result',{competitionId:competition,athleteId:athlete,teamId:'',fixtureId:'',outcome:'Placed',position:'1',resultDate:'2026-09-01',evidenceNote:'Official signed results'});const publicResult=(await pg.query("select payload from registry where collection='results' and id=$1",[r])).rows[0].payload;assert.equal(publicResult.recordSource,'Association-reported');assert.equal(Number((await call('sport_rankings'))[0].total_points),10);});
 await t.test('round robin has every pair once, including odd-team byes, and rolls back duplicate generation',async()=>{await login('association');const c=await save('Competition',{name:'Round robin','discipline':'Bowls',category:'Open',season:'2026',startDate:'2026-01-01',endDate:'2026-12-31',level:'National'});await call('transition_sport_record',[c,'Submitted','']);await login('reviewer');await call('transition_sport_record',[c,'Approved','']);await login('association');const id=(await call('generate_tournament',[c,teams.slice(0,3),'Round robin','2026-09-01T06:00:00Z',60,'Test green']))[0].generate_tournament;const matches=(await pg.query('select * from tournament_matches where tournament_id=$1',[id])).rows;assert.equal(matches.length,3);assert.equal(new Set(matches.map(m=>[m.home_team,m.away_team].sort().join())).size,3);await assert.rejects(()=>call('generate_tournament',[c,teams.slice(0,3),'Round robin','2026-09-01T06:00:00Z',60,'Test green']),/already has fixtures/);});
 await t.test('knockout builds all rounds, advances from saved winning results and creates the final',async()=>{await login('association');tourney=(await call('generate_tournament',[competition,teams,'Knockout','2026-09-02T06:00:00Z',60,'Test green']))[0].generate_tournament;const matches=(await pg.query('select * from tournament_matches where tournament_id=$1 order by round,slot',[tourney])).rows;assert.equal(matches.length,3);assert.equal(matches.filter(m=>m.fixture_id).length,2);for(const m of matches.filter(m=>m.round===1)){await assert.rejects(()=>call('advance_tournament',[m.id,m.home_team]),/Save the winning/);await save('Result',{competitionId:competition,athleteId:'',teamId:m.home_team,fixtureId:m.fixture_id,outcome:'Won',position:'',resultDate:'2026-09-02',evidenceNote:'Match sheet'});await call('advance_tournament',[m.id,m.home_team]);}const final=(await pg.query('select * from tournament_matches where tournament_id=$1 and round=2',[tourney])).rows[0];assert(final.fixture_id&&final.home_team&&final.away_team);});
 await t.test('advanced brackets reject changed winners, duplicate winners and archived generated fixtures',async()=>{await login('association');const m=(await pg.query('select * from tournament_matches where tournament_id=$1 and round=1 order by slot',[tourney])).rows[0];const r=(await pg.query("select * from sport_records where kind='Result' and payload->>'fixtureId'=$1",[m.fixture_id])).rows[0];await assert.rejects(()=>save('Result',{...r.payload,outcome:'Lost'},r.id),/advanced a knockout/);await assert.rejects(()=>save('Result',{...r.payload,teamId:m.away_team}),/already has a winning/);await assert.rejects(()=>call('transition_sport_record',[m.fixture_id,'Archived','Remove match']),/dependent|Generated fixtures/);});
 await t.test('multiple funding/travel/clearance requests remain independent private cases',async()=>{await login('association');for(let i=0;i<2;i++)await pg.query("insert into submissions(association_id,created_by,kind,period,payload) values('TEST-A',$1,'Funding request','2026',$2)",[ids.association,{title:'Funding '+i,summary:'Budget for national competition',requestedAmount:'100000',currency:'MWK'}]);await login('other');assert.equal((await pg.query("select * from submissions where kind='Funding request'")).rows.length,0);});
 await t.test('awards rubric, shortlist and official assignments lock after judging starts',async()=>{await login('admin');await pg.exec("insert into award_cycles(year,age_reference_date,scoring_policy,amendment_approved,policy_disclosed,nomination_status) values(2026,'2026-12-31','judges_only',true,true,'Open')");await call('configure_award_category',[2026,'sportswoman',[{label:'Excellence',weight:60},{label:'Leadership',weight:40}],2]);await call('assign_award_official',[2026,'sportswoman',ids.judge,'judge']);await call('assign_award_official',[2026,'sportswoman',ids.judge2,'judge']);await call('assign_award_official',[2026,'sportswoman',ids.auditor,'auditor']);await login('association');for(const [i,name] of ['Thoko Banda','Mphatso Phiri'].entries()){const id='20000000-0000-0000-0000-'+String(i+1).padStart(12,'0');nominees.push(id);await pg.query("insert into submissions(id,association_id,created_by,kind,period,payload,document_path) values($1,'TEST-A',$2,'Award nomination','2026',$3,$4)",[id,ids.association,{categoryId:'sportswoman',nomineeName:name,description:'Athlete',motivation:'Exceptional performance',declaration:true},'TEST-A/'+id+'.pdf']);await call('transition_submission',[id,'Submitted','']);}await login('reviewer');for(const id of nominees)await call('transition_submission',[id,'Approved','Eligible']);await login('admin');for(const id of nominees)await call('shortlist_award',[2026,'sportswoman',id,true]);await call('set_award_phase',[2026,'sportswoman','Judging']);await assert.rejects(()=>call('configure_award_category',[2026,'sportswoman',[{label:'Changed',weight:100}],2]),/locked/);});
 let candidates;
 await t.test('judge ballots seal once; judges cannot read other ballots or unassigned evidence',async()=>{await login('judge');candidates=(await pg.query('select * from award_candidates order by nominee_name')).rows;assert.equal((await pg.query("select * from submissions where kind='Award nomination'")).rows.length,2);for(const [i,ca] of candidates.entries())await call('submit_award_ballot',[ca.id,i?[9,8]:[7,7],'Reviewed achievements and leadership evidence',true]);await assert.rejects(()=>call('submit_award_ballot',[candidates[0].id,[10,10],'Replacement ballot should be refused',true]),/duplicate/);await login('judge2');assert.equal((await pg.query('select * from award_ballots')).rows.length,0);for(const [i,ca] of candidates.entries())await call('submit_award_ballot',[ca.id,i?[8,8]:[6,7],'Independent evidence assessment',true]);await login('association');assert.equal((await pg.query('select * from award_ballots')).rows.length,0);await assert.rejects(()=>call('submit_award_ballot',[candidates[0].id,[10,10],'Tampering ballot',true]),/Assigned judge/);});
 await t.test('verified fan votes are private, one per category, with zero official weight',async()=>{await login('admin');await call('set_fan_poll',[2026,'sportswoman',true]);await login('unverified');await assert.rejects(()=>call('cast_fan_vote',[candidates[0].id]),/verified email/);await login('fan');await call('cast_fan_vote',[candidates[0].id]);await assert.rejects(()=>call('cast_fan_vote',[candidates[1].id]),/duplicate/);await assert.rejects(()=>pg.query('select * from award_fan_votes'),/permission denied/);await login('anon');const publicRows=await call('public_awards');assert.equal(publicRows[0].public_awards.results,null);assert.equal(publicRows[0].public_awards.candidates[0].votes,null);});
 await t.test('only an assigned independent auditor certifies; council publishes a fingerprinted snapshot',async()=>{await login('admin');await call('set_fan_poll',[2026,'sportswoman',false]);await call('set_award_phase',[2026,'sportswoman','Auditing']);await assert.rejects(()=>call('certify_award',[2026,'sportswoman','I checked all ballots and verified totals.']),/independent auditor/);await login('auditor');assert.equal((await pg.query('select * from award_ballots')).rows.length,4);const audit=(await call('certify_award',[2026,'sportswoman','I checked eligibility, assignments, ballots, criteria weights and recomputed every total.']))[0].certify_award;assert.equal(audit.fingerprint.length,64);assert.equal(audit.results[0].name,'Thoko Banda');assert.equal(Number(audit.results[0].score),83);await login('admin');await call('set_award_phase',[2026,'sportswoman','Published']);await login('anon');const published=(await call('public_awards'))[0].public_awards;assert.equal(published.fingerprint,audit.fingerprint);assert.equal(published.results[0].name,'Thoko Banda');assert(!JSON.stringify(published).includes('judgeId'));assert.equal(published.candidates.find(c=>c.id===candidates[0].id).votes,1);});
 await t.test('full installer rerun preserves new roles, repeated requests and certified results',async()=>{await pg.exec('reset role');await pg.exec(installer);assert.equal((await pg.query('select count(*)::integer n from award_audits')).rows[0].n,1);assert.equal((await pg.query("select count(*)::integer n from submissions where kind='Funding request'")).rows[0].n,2);});
 await pg.close();
});
